version: '3'
services:
  airbag:
    image: ${SIDECAR_IMAGE_NAME}
    container_name: airbag
    depends_on:
      - valid_auth_server
      - auth_server_with_different_issuer
      - protected_api
      - opa
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AUTHORITY=http://valid_auth_server
      - ISSUER=http://valid_auth_server
      - AUDIENCE=api1
      - AUTHORITY_ANOTHER=http://another_valid_auth_server
      - ISSUER_ANOTHER=http://another_valid_auth_server
      - AUDIENCE_ANOTHER=api1
      - BACKEND_HOST_NAME=protected_api
      - BACKEND_SERVICE_PORT=8080
      - COLLECT_METRICS=false
      - UNAUTHENTICATED_ROUTES=/isAlive,/foo*
      - OPA_QUERY_PATH=protected_api/allow
      - OPA_MODE=Enabled
      - OPA_URL=http://opa:8181

  airbag-without-aud-validation:
    image: ${SIDECAR_IMAGE_NAME}
    container_name: airbag-without-aud-validation
    depends_on:
      - valid_auth_server
      - auth_server_with_different_issuer
      - protected_api
      - opa
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AUTHORITY_ANOTHER=http://valid_auth_server
      - ISSUER_ANOTHER=http://valid_auth_server
      - VALIDATE_AUDIENCE_ANOTHER=false
      - BACKEND_HOST_NAME=protected_api
      - BACKEND_SERVICE_PORT=8080
      - COLLECT_METRICS=false
      - UNAUTHENTICATED_ROUTES=/isAlive,/foo*
      - OPA_QUERY_PATH=protected_api/allow
      - OPA_MODE=Enabled
      - OPA_URL=http://opa:8181

  valid_auth_server:
    image: ${SAMPLE_AUTH_IMAGE_NAME}
    container_name: valid_auth_server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ISSUER=http://valid_auth_server

  another_valid_auth_server:
    image: ${SAMPLE_AUTH_IMAGE_NAME}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ISSUER=http://another_valid_auth_server

  auth_server_with_different_issuer:
    image: ${SAMPLE_AUTH_IMAGE_NAME}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ISSUER=http://someuri.com:1234

  auth_server_with_different_signature:
    image: ${SAMPLE_AUTH_IMAGE_NAME}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ISSUER=http://valid_auth_server

  protected_api:
    image: jmalloc/echo-server

  opa:
    image: openpolicyagent/opa
    container_name: opa
    command: run --server /policies
    volumes:
      - '${REPOSITORY_VOLUME}/open-policy-agent:/policies'
